### PR TITLE
Fix setup 

### PR DESCRIPTION
**Pull request by tom-doerr**
Currently the setup instructions are not longer working.
`pip3 install $(python3 util/taskcluster.py --decoder)`
fails with `HTTP error 404 while getting https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.4.1.cpu-ctc/artifacts/public/ds_ctcdecoder-0.4.1-cp35-cp35m-manylinux1_x86_64.whl
`
Mozilla most likely removed that package, as they did with previous versions.
To fix this issue and to make the setup easier, I wrote dockerfiles that compile the decoder and set up the environment.

### CODE REVIEW

**Comment by ENegatiVY** [comment]
Thanks. Your work helps me a lot.

**Comment by carlini** [comment]
Hi Tom, thanks for keeping this thing up to date and helping people use it. I'm going to merge this in--are there any other tweaks you'd want to apply before I do so? (Clearly if there are after I make the merge, you can always make another PR. I just want to check to start.)

**Comment by tom-doerr** [comment]
Hi Nicholas, that's it for now. Yesterday I only made it more explicit how to set up docker, in case you were wondering about that.

**Comment by tom-doerr** [comment]
Improved the readme a bit.

**Comment by carlini** [comment]
I merged this manually so I could keep the original instructions below your improved ones. Thanks for this, it's much simpler.

**Pull request closed without merging**
